sudo: false
dist: trusty
language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_TRAVISCI=phpcs
    - php: 7.1
      env: WP_TRAVISCI=phpcs
    - php: 7.0
      env: WP_TRAVISCI=phpcs

before_script:
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer install;
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      find . -name '*.php' ! -path "./vendor/*" ! -path "./wp-content/*" -print0 | xargs -0 -n 1 -P 4 php -l
      ./vendor/bin/phpcs --runtime-set testVersion $TRAVIS_PHP_VERSION
    fi

notifications:
  email: false
